Feat/main page
ssttv/twitter-demo-frontend pull request #2
Opened 2018-06-16 20:31 UTC by ssttv

Requesting first evaluation

2018-06-18 07:27 UTC, imevro requested changes

2018-06-18 07:27 UTC, evgenyrodionov commented on src/trash/App.1.js
> +import React, { Component } from "react";
если это треш, то зачем ты это оставил в репозитории?

2018-06-18 07:27 UTC, evgenyrodionov commented on package.json
> +    "eslint-config-airbnb": "^16.1.0",
это дев депенденси

2018-06-18 07:27 UTC, evgenyrodionov commented on public/avatar.svg
> +<image id="image0" width="400" height="400" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAAXNSR0IArs4c6QAAGAxJREFUeAHt3VnMXlP7B+DV4jNG1FAhSEhUJRygQQQxpMGJkEgFFWMl1
зачем ты пнг засунул в свг?

2018-06-18 07:27 UTC, evgenyrodionov commented on src/App.js
> +import Page from "./Page";
пейдж что?

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Header.js
> +import React, { Component } from "react";
`Header/Header.js` → `Header/index.js` и импортишь как `import Header from './Header'`

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Header.js
> +  display: grid;
нет

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Navigation/Navigation.js
> +/* const Home = styled.div`
мусор нужно выносить

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Navigation/Navigation.js
> +  &.normal {
что это

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Navigation/Navigation.js
> +  background-image: url(${search});
зачем? нет

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Header/Navigation/Navigation.js
> +  position: absolute;
нет

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Main/Main.js
> +import React from "react";
мейн? что мейн?

2018-06-18 07:27 UTC, evgenyrodionov commented on src/Page/Main/Main.js
> +  <div>
зачем этот див?

2018-06-20 21:01 UTC, imevro requested changes

2018-06-20 21:01 UTC, evgenyrodionov commented on src/App.js
> +import Interface from "./Interface";
вообще нет

2018-06-20 21:01 UTC, evgenyrodionov commented on src/Interface/Content/ProfileInfo/LeftSidebar.js
> +        <PhotoVideoList>
не вижу переиспользуемости компонентов, иди читай про пропы

2018-06-20 21:01 UTC, evgenyrodionov commented on src/Interface/Header/StatUnit.js
> +    <StatLink to={link} activeClassName="active" exact>
по дефолту activeClassName и так `active`

2018-06-20 21:01 UTC, evgenyrodionov commented on src/Interface/index.js
> +  // <div></div> здесь служит закрывающим тегом для хедера и хелмета
почитай про реакт фрагмент

2018-06-20 21:37 UTC, ssttv commented on src/App.js
> +import Interface from "./Interface";
Вообще неподходящее название? Хорошо ли будет тогда использовать ProfilePage или Profile - раз уж у меня рассматривается в этом демо только личная страница.

2018-06-25 15:19 UTC, imevro approved these changes

2018-06-25 15:20 UTC, merged

2018-06-25 15:20 UTC, evgenyrodionov commented
Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап

---

в след раз если будут коммиты после ревью — не пропущу