Feat/api integration
ssttv/twitter-demo-frontend pull request #3
Opened 2018-06-27 08:43 UTC by ssttv

В массивы оформлены списки с рекомендациями фолловеров и трендами (последние - коряво), создан словарь страниц и пользователей, настроен переход на шаблон (dummy).

2018-06-27 21:27 UTC, imevro requested changes

2018-06-27 21:27 UTC, imevro commented on .prettierrc
> +{
преттир не нужно настраивать

2018-06-27 21:27 UTC, imevro commented on src/App.js
> +          {pages.map(page => (
вот такого программирования не надо, оно слишком неочевидно — нет понимания архитектуры проекта

2018-06-27 21:27 UTC, imevro commented on src/App.js
> +          <Route path="/:handle" component={Profile} />
:handle не оч нейминг

2018-06-27 21:27 UTC, imevro commented on src/Profile/Content/ProfilePosts/Trend.js
> +  /* Simplified for mapping below
мусор нужно выносить

2018-06-29 22:15 UTC, imevro requested changes

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/Artefacts.js
> +  margin: -8px 0 0 -8px;
выглядит как хак

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/Artefacts.js
> +import React from "react";
что такое _артефактс_?

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/Artefacts.js
> +          <PhotoVideoLink to={artefact.to}>
зачем эти префиксы

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/CommunitySidebar.js
> +import React from "react";
зачем отдельный файл коммунитисидебар?

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/SharedFollowers.js
> +  margin: -8px 0 0 -8px;
опять же

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/SharedFollowers.js
> +          {follower.id <= 10 && (
метод filter?

2018-06-29 22:15 UTC, evgenyrodionov commented on src/Profile/Content/ProfileInfo/Title.js
> +    <TitleText>{children}</TitleText>
ты и так в компоненте тайтл, ну зачем ты делаешь эти бесконечные префиксы тайтл

2018-06-29 22:15 UTC, evgenyrodionov commented on src/urlDictionary.js
> +    to: "/moments"
я же сказал убрать программирование ссылок конфигом?

2018-06-30 20:55 UTC, ssttv commented
Демо https://twitter-demo-frontend-mmsdwtzden.now.sh

2018-07-05 14:12 UTC, imevro requested changes

2018-07-05 14:12 UTC, evgenyrodionov commented on src/Header/Crumb.js
> +      <CrumbIcon src={src} alt={alt} />
зачем будучи в файле Crumb делать столько префиксов Crumb Crumb Crumb Crumb

2018-07-05 14:12 UTC, evgenyrodionov commented on src/Profile/Posts/index.js
> +    return `${textElement} `;
этим не нужно заниматься, потому что с апи будет приходить готовая разметка

2018-07-06 03:19 UTC, ssttv commented
Новое демо https://twitter-demo-frontend-htqslspwzv.now.sh/EveryInteract

2018-07-06 20:17 UTC, imevro approved these changes

2018-07-20 21:13 UTC, merged