Feat/flow and redux
ssttv/twitter-demo-frontend pull request #6
Opened 2018-07-13 04:41 UTC by ssttv

Last week pull request

2018-07-14 21:21 UTC, ssttv commented
https://twitter-demo-frontend-shfyspbwvt.now.sh/1
На тот случай, если у Travis что-то пошло не так.

2018-07-15 06:30 UTC, ssttv commented
Новый now.sh, в этот раз Travis его автоматически сделал: https://twitter-demo-frontend-cwpehcpfbm.now.sh/

2018-07-16 22:07 UTC, imevro requested changes

2018-07-16 22:07 UTC, evgenyrodionov commented on package.json
> +    "flow-bin": "^0.76.0",
а флоу-тупед где

2018-07-16 22:07 UTC, evgenyrodionov commented on src/Profile/index.js
> +    : "";
как-то дерьмово выглядит

2018-07-16 22:07 UTC, evgenyrodionov commented on src/Profile/index.js
> +  username: string,
мусор же

2018-07-16 22:07 UTC, evgenyrodionov commented on src/Profile/index.js
> +    let userId: ?string = id;
давай без мутабельности

2018-07-18 01:50 UTC, ssttv commented
Демо: https://twitter-demo-frontend-kezsnmojqj.now.sh/

2018-07-18 02:26 UTC, ssttv commented on package.json
> +    "flow-bin": "^0.76.0",
Flow-typed вставлен ниже в package.json

2018-07-18 20:45 UTC, imevro requested changes

2018-07-18 20:45 UTC, evgenyrodionov commented on src/Profile/Posts/index.js
> +    };
что это за функция? что она делает? какая-то дичь

2018-07-20 08:35 UTC, ssttv commented
этот пуллреквест не аппрувнут, но он последний

2018-07-20 20:32 UTC, imevro approved these changes

2018-07-20 20:32 UTC, evgenyrodionov commented
Мерджи через сквош один за одним (D → C → B → A (это мастер))

2018-07-20 21:10 UTC, merged